#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6446066593                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : cn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/cn/app/charming-%E8%8E%AB%E6%96%AF/id6446066593                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://oneyear2.kittenyang.com/charming/Charming.dmg                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Charming-莫斯                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 支持 GPT-4-32k 的 AI 聊天客户端

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kitten Yang                                
your_link                                 : 
your_city                                 : CA                                
email_address                             : imkittenyang@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : KittenYang
github_username                           : KittenYang
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 免 API Key
    description                           : 支持原版 4.0 8k、32k 接口，无论你在那里，全球顺畅使用！
    fontawesome_icon_name                 : magic
    
  - title                                 : 内置160+ prompts 预设
    description                           : 网络热门 prompt 实时更新，随时体验
    fontawesome_icon_name                 : mobile

  - title                                 : 支持语音对话
    description                           : 多国语音，甚至方言
    fontawesome_icon_name                 : play-circle

  - title                                 : 支持 iCloud 同步
    description                           : iPad / Mac / iPhone 对话记录同步
    fontawesome_icon_name                 : sync

  - title                                 : 集成 Siri
    description                           : 支持与 Siri 的多轮对话，且可以保存与 Siri 的对话！
    fontawesome_icon_name                 : adjust
  
  - title                                 : 导出模板
    description                           : 支持导出模板，对方导入后可继续聊天
    fontawesome_icon_name                 : star

  - title                                 : 常用命令
    description                           : 支持独创的「常用命令」功能，快速发送常用指令片段！ 
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : 参数自定义
    description                           : 支持全部 API 参数自定义，最大程度支持 pro 玩家微调
    fontawesome_icon_name                 : link

  - title                                 : Raycast
    description                           : 全网第一时间和 Raycast 打通的 GPT 客户端，Mac 上随叫随到 https://www.raycast.com/KittenYang/charming-chatgpt
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
